apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  ################# Payment Service #################
  - name: payment-service
#    namespace: neo-platform
    envs:
      - payment-service/.env

# Generator Option
generatorOptions:
  disableNameSuffixHash: true